[package]
name = "pgpq-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
pgpq = { path = "../core" }
clap = "3.0"
arrow = "46.0.0"
parquet = "46.0.0"
bytes = "1.7.1"

[[bin]]
name = "pgpq"
path = "src/main.rs"
